[book]
authors = ["slofl"]
language = "en"
multilingual = false
src = "src"
title = ""

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
additional-css = ["custom.css"]

[output.html.print]
enable = false
page-break = false